version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api-platform-db
      POSTGRES_USER: user
    volumes:
      - ./db-data-postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  frontend:
    image: node:18-alpine
    container_name: frontend
    restart: always
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn dev --port 3000 --host"