version: '3'

services:
  database:
      image: postgres:15-alpine
      restart: always
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api-platform-db
          POSTGRES_USER: user
      volumes:
        - ./db-data-postgres:/var/lib/postgresql/data:rw
      ports:
        - target: 5432
          published: 5432
          protocol: tcp

  adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080

