controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']

docs:
    path: /api/docs
    controller: api_platform.swagger.action.ui
    condition: "false"

api_refresh_token:
    path: /api/token/refresh