version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api-platform-db
      POSTGRES_USER: user
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    ports:
      - 5432:5432

volumes:
  db_data: