# Voici un exemple de fichier github action pour déployer une application Symfony sur Heroku en utilisant les actions de Heroku et de PHP:
name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: back

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    
    - name: Install Composer dependencies
      run: composer install

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-platform-challenge"
          appdir: back
          heroku_email: "raimbaultfantin94@gmail.com"
          procfile: "web: heroku-php-apache2 public/"
