# Voici un exemple de fichier github action pour déployer une application Symfony sur Heroku en utilisant les actions de Heroku et de PHP:
name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer install --no-interaction --no-progress --no-scripts

    - name: Pull images
      run: docker compose pull --ignore-pull-failures || true
    - name: Start services
      run: |
        docker-compose build
        docker-compose up -d

    ## create .env file
    - name: Set env variables
      id: set-env
      run: |
          touch .env
          printf ${{ secrets.ENV_FILE }} | base64 --decode > .env

    - name: Wait for services
      run: sleep 10

    - name: Create test database
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:update --env=test --force

    - name: PHPUnit
      run: php bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-platform-challenge"
          appdir: back
          heroku_email: "raimbaultfantin94@gmail.com"
          procfile: "web: heroku-php-apache2 public/"
